<a href="https://colab.research.google.com/github/udaybhaskar29/Calorie-burnt-predictor/blob/main/house_price_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git --version

git version 2.43.0

In [2]:
!git config --global user.name "Uday Bhaskar Dutta"
!git config --global user.email "uday090151@gmail.com"

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.set_option('display.max_rows',None)
pd.set_option('display.max_columns',None)

In [ ]:
df = pd.read_csv('flats.csv')
df.sample(5)

,property_name,link,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating,property_id
2981,2 BHK Flat in Sector 99A Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Laxmi Apartment sector 99A Gurgaon,30 Lac,"₹ 4,615/sq.ft.",Super Built up area 650(60.39 sq.m.)Carpet are...,2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Tower 08 Flat No. 0404, Sector 99A Gurgaon, Gu...",4th of 10 Floors,NaN,0 to 1 Year Old,NaN,Dear buyer this is a affordable housing societ...,NaN,"['Security / Fire Alarm', 'Intercom Facility',...","['Safety3 out of 5', 'Lifestyle3 out of 5', 'E...",X62112670
1410,3 BHK Flat in Sector 82A Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,DLF The Primus3.9 ★,1.87 Crore,"₹ 10,394/sq.ft.",Super Built up area 1799(167.13 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,Pooja Room,"198, Sector 82A Gurgaon, Gurgaon, Haryana",31st of 32 Floors,East,5 to 10 Year Old,"['Sapphire 83', 'NH 48', 'Cambridge Montessori...",This 3 bhk apartment is available for sale in ...,NaN,"['Power Back-up', 'Intercom Facility', 'Lift(s...","['Green Area5 out of 5', 'Construction4.5 out ...",O68656188
1732,2 BHK Flat in Sector 84 Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Antriksh Heights3.7 ★,60 Lac,"₹ 5,000/sq.ft.",Super Built up area 1200(111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,NaN,"Antriksh Heights, Sector 84 Gurgaon, Gurgaon, ...",14th of 19 Floors,North,1 to 5 Year Old,"['Old Bengali Market', 'MatriKiran High School...",Corner unit sun facing for sale call for more ...,NaN,"['Power Back-up', 'Lift(s)', 'High Ceiling Hei...","['Green Area4.5 out of 5', 'Construction3.5 ou...",N69974042
1582,3 BHK Flat in Sector 70 Gurgaon,https://www.99acres.com/3-bhk-bedroom-apartmen...,Shree Vardhman Victoria3.8 ★,1.63 Crore,"₹ 8,358/sq.ft.",Super Built up area 1950(181.16 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,"Servant Room,Others","3 Bhk, Sector 70 Gurgaon, Gurgaon, Haryana",5th of 15 Floors,East,0 to 1 Year Old,"['Airia Mall', 'Golf Course Extn Road', 'Sohna...",Looking for a 3 bhk property for sale in gurga...,"['4 AC', '1 Modular Kitchen', 'No Bed', 'No Ch...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction5 out of...",W69217906
2457,2 BHK Flat in Sector 88B Gurgaon,https://www.99acres.com/2-bhk-bedroom-apartmen...,Vatika Xpressions,92 Lac,"₹ 6,815/sq.ft.",Built Up area: 1350 (125.42 sq.m.)Carpet area:...,2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sector 88b, Sector 88B Gurgaon, Gurgaon, Haryana",3rd of 3 Floors,NaN,Within 6 months,"['Dwarka Expressway', 'Adarsh public school,Ga...",2bhk multistorey apartment for resale in vatik...,NaN,"['Feng Shui / Vaastu Compliant', 'Intercom Fac...",NaN,V67904060

In [ ]:
df.shape

(3008, 20)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3008 entries, 0 to 3007
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   property_name    3008 non-null   object
 1   link             3008 non-null   object
 2   society          3007 non-null   object
 3   price            3007 non-null   object
 4   area             2996 non-null   object
 5   areaWithType     3008 non-null   object
 6   bedRoom          3008 non-null   object
 7   bathroom         3008 non-null   object
 8   balcony          3008 non-null   object
 9   additionalRoom   1694 non-null   object
 10  address          3002 non-null   object
 11  floorNum         3006 non-null   object
 12  facing           2127 non-null   object
 13  agePossession    3007 non-null   object
 14  nearbyLocations  2913 non-null   object
 15  description      3008 non-null   object
 16  furnishDetails   2203 non-null   object
 17  features         2594 non-null   object
 18  rating           2676 non-null   object
 19  property_id      3008 non-null   object
dtypes: object(20)
memory usage: 470.1+ KB

In [ ]:
#check for duplicate rows
df.duplicated().sum()

np.int64(0)

In [ ]:
df.isnull().sum()

property_name         0
link                  0
society               1
price                 1
area                 12
areaWithType          0
bedRoom               0
bathroom              0
balcony               0
additionalRoom     1314
address               6
floorNum              2
facing              881
agePossession         1
nearbyLocations      95
description           0
furnishDetails      805
features            414
rating              332
property_id           0
dtype: int64

In [ ]:
df.drop(columns=['link','property_id'],inplace=True)

In [ ]:
df.head()

,property_name,society,price,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [ ]:
# rename columns
df.rename(columns={'area':'price_per_sqft'},inplace=True)
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,Apna Enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,Tulsiani Easy in Homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,Smart World Orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,Parkwood Westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [ ]:
df['society'].value_counts().shape

(636,)

In [ ]:
import re
df['society'] = df['society'].apply(lambda name:re.sub(r'\d+(\.\d+)?\s?★','',str(name)).strip()).str.lower()

In [ ]:
df['society'].value_counts().shape

(602,)

In [ ]:
# Price
df['price'].value_counts()

price
1.25 Crore          79
1.1 Crore           61
1.4 Crore           60
1.2 Crore           59
1.5 Crore           59
90 Lac              58
1.3 Crore           57
95 Lac              53
2 Crore             51
1.75 Crore          47
1 Crore             46
1.6 Crore           43
1.35 Crore          41
1.9 Crore           40
1.55 Crore          40
75 Lac              38
1.65 Crore          38
1.7 Crore           37
1.8 Crore           37
80 Lac              36
2.2 Crore           34
1.15 Crore          33
50 Lac              33
85 Lac              31
1.45 Crore          31
1.05 Crore          30
60 Lac              29
40 Lac              29
2.5 Crore           29
2.1 Crore           26
45 Lac              26
65 Lac              25
35 Lac              23
1.85 Crore          23
2.35 Crore          23
3 Crore             22
70 Lac              21
2.25 Crore          20
55 Lac              20
3.5 Crore           19
2.3 Crore           18
2.4 Crore           18
30 Lac              17
2.65 Crore          16
2.6 Crore           15
1.38 Crore          15
2.45 Crore          14
3.4 Crore           14
2.15 Crore          14
82 Lac              13
3.25 Crore          13
92 Lac              13
38 Lac              13
78 Lac              13
2.7 Crore           13
1.32 Crore          13
5 Crore             12
42 Lac              12
1.95 Crore          12
1.42 Crore          12
2.8 Crore           12
25 Lac              11
88 Lac              11
Price on Request    11
32 Lac              11
1.08 Crore          11
1.28 Crore          10
26 Lac              10
87 Lac              10
1.78 Crore          10
1.12 Crore          10
2.55 Crore          10
28 Lac              10
2.85 Crore           9
1.72 Crore           9
1.68 Crore           9
3.45 Crore           9
4 Crore              9
2.05 Crore           9
99 Lac               9
36 Lac               9
22 Lac               9
48 Lac               8
20 Lac               8
2.75 Crore           8
4.25 Crore           8
86 Lac               8
27 Lac               8
1.26 Crore           8
6.5 Crore            8
1.54 Crore           8
1.18 Crore           8
1.76 Crore           8
3.2 Crore            8
6 Crore              8
98 Lac               8
56 Lac               8
39 Lac               7
2.9 Crore            7
72 Lac               7
97 Lac               7
1.27 Crore           7
46 Lac               7
1.36 Crore           7
3.7 Crore            7
1.99 Crore           7
1.19 Crore           7
1.02 Crore           7
1.29 Crore           7
3.3 Crore            7
79 Lac               7
1.16 Crore           6
2.95 Crore           6
1.14 Crore           6
96 Lac               6
3.05 Crore           6
1.51 Crore           6
1.34 Crore           6
1.13 Crore           6
71.5 Lac             6
1.07 Crore           6
5.5 Crore            6
1.59 Crore           6
1.98 Crore           6
21 Lac               6
54 Lac               6
1.01 Crore           6
43 Lac               6
37 Lac               6
3.35 Crore           6
4.1 Crore            6
1.49 Crore           6
1.39 Crore           6
3.65 Crore           6
3.9 Crore            6
1.24 Crore           5
6.75 Crore           5
1.33 Crore           5
29 Lac               5
1.47 Crore           5
2.22 Crore           5
1.69 Crore           5
64 Lac               5
1.91 Crore           5
4.5 Crore            5
3.75 Crore           5
1.43 Crore           5
1.82 Crore           5
1.83 Crore           5
49 Lac               5
1.92 Crore           5
66 Lac               5
24 Lac               5
1.93 Crore           5
68 Lac               5
1.62 Crore           5
1.79 Crore           5
2.29 Crore           5
93 Lac               5
2.78 Crore           5
2.12 Crore           5
1.44 Crore           5
1.17 Crore           5
1.23 Crore           4
58 Lac               4
41.5 Lac             4
1.22 Crore           4
1.48 Crore           4
1.71 Crore           4
6.15 Crore           4
7 Crore              4
4.85 Crore           4
4.3 Crore            4
1.66 Crore           4
31 Lac               4
3.1 Crore            4
67 Lac               4
36.5 Lac             4
33 Lac               4
73 Lac               4
89 Lac               4
28.5 Lac             4
1.58 Crore           4
5.9 Crore            4
5.6 Crore            4
2.09 Crore           4
1.31 Crore           4
74 Lac               4
1.37 Crore           4
1.52 Crore           4
5.25 Crore           4
1.73 Crore           4
62 Lac               4
3.6 Crore            4
1.77 Crore           4
1.64 Crore           4
3.95 Crore           4
4.75 Crore           3
3.8 Crore            3
1.04 Crore           3
2.28 Crore           3
2.03 Crore           3
1.09 Crore           3
2.08 Crore           3
1.67 Crore           3
1.57 Crore           3
2.36 Crore           3
91 Lac               3
4.8 Crore            3
2.51 Crore           3
3.15 Crore           3
2.24 Crore           3
52 Lac               3
69 Lac               3
83 Lac               3
1.21 Crore           3
2.01 Crore           3
94 Lac               3
72.5 Lac             3
5.8 Crore            3
1.63 Crore           3
3.85 Crore           3
1.41 Crore           3
84 Lac               3
34 Lac               3
2.33 Crore           3
51 Lac               3
2.79 Crore           3
1.88 Crore           3
64.5 Lac             3
3.49 Crore           3
4.2 Crore            3
47 Lac               3
56.2 Lac             2
3.55 Crore           2
7.5 Crore            2
27.1 Lac             2
11 Crore             2
4.55 Crore           2
2.87 Crore           2
2.26 Crore           2
87.5 Lac             2
52.56 Lac            2
2.14 Crore           2
2.99 Crore           2
1.56 Crore           2
2.58 Crore           2
2.57 Crore           2
5.2 Crore            2
5.7 Crore            2
2.13 Crore           2
1.46 Crore           2
8 Crore              2
8.5 Crore            2
2.17 Crore           2
59 Lac               2
3.29 Crore           2
71 Lac               2
6.2 Crore            2
2.23 Crore           2
53.5 Lac             2
2.52 Crore           2
4.49 Crore           2
2.04 Crore           2
27.75 Lac            2
4.7 Crore            2
88.5 Lac             2
2.41 Crore           2
2.02 Crore           2
4.26 Crore           2
3.32 Crore           2
4.6 Crore            2
3.21 Crore           2
25.5 Lac             2
14 Crore             2
4.45 Crore           2
98.5 Lac             2
1.87 Crore           2
2.91 Crore           2
53 Lac               2
31.5 Lac             2
77.5 Lac             2
41 Lac               2
3.19 Crore           1
5.31 Crore           1
4.95 Crore           1
4.02 Crore           1
97.04 Lac            1
37.5 Lac             1
68.85 Lac            1
98.88 Lac            1
2.69 Crore           1
2.54 Crore           1
54.8 Lac             1
3.98 Crore           1
94.5 Lac             1
2.44 Crore           1
82.5 Lac             1
61 Lac               1
29.8 Lac             1
6.02 Crore           1
7.9 Crore            1
3.23 Crore           1
15 Crore             1
7.8 Crore            1
1.97 Crore           1
39.5 Lac             1
11.25 Crore          1
7.15 Crore           1
2.82 Crore           1
54.99 Lac            1
6.44 Crore           1
1.11 Crore           1
8.25 Crore           1
31.75 Lac            1
55.6 Lac             1
98.1 Lac             1
2.63 Crore           1
55.5 Lac             1
5.4 Crore            1
3.39 Crore           1
95.75 Lac            1
3.46 Crore           1
3.63 Crore           1
4.67 Crore           1
2.37 Crore           1
4.4 Crore            1
66.99 Lac            1
6.3 Crore            1
23 Lac               1
5.49 Crore           1
2.98 Crore           1
4.63 Crore           1
2.34 Crore           1
6.16 Crore           1
5.3 Crore            1
2.72 Crore           1
4.78 Crore           1
2.21 Crore           1
2.48 Crore           1
89.5 Lac             1
99.5 Lac             1
3.83 Crore           1
3.79 Crore           1
3.67 Crore           1
71.2 Lac             1
27.5 Lac             1
23.5 Lac             1
4.79 Crore           1
6.25 Crore           1
35.5 Lac             1
2.11 Crore           1
1.06 Crore           1
4.94 Crore           1
10.75 Crore          1
81 Lac               1
26.1 Lac             1
9.14 Crore           1
8.35 Crore           1
20.5 Lac             1
17.5 Lac             1
24.5 Lac             1
10 Crore             1
6.1 Crore            1
5.75 Crore           1
2.77 Crore           1
7.56 Crore           1
79.9 Lac             1
68.5 Lac             1
85.5 Lac             1
93.75 Lac            1
94.25 Lac            1
80.5 Lac             1
2.97 Crore           1
29.99 Lac            1
4.86 Crore           1
2.62 Crore           1
52.5 Lac             1
90.5 Lac             1
42.5 Lac             1
2.61 Crore           1
65.5 Lac             1
53.2 Lac             1
47.5 Lac             1
4.52 Crore           1
8.44 Crore           1
1.84 Crore           1
13.2 Crore           1
4.16 Crore           1
1.74 Crore           1
4.21 Crore           1
97.5 Lac             1
2.38 Crore           1
2.49 Crore           1
2.64 Crore           1
63.4 Lac             1
2.06 Crore           1
2.07 Crore           1
44 Lac               1
2.32 Crore           1
1.86 Crore           1
85.75 Lac            1
87.99 Lac            1
86.99 Lac            1
2.92 Crore           1
9.3 Crore            1
5.15 Crore           1
49.5 Lac             1
9.2 Crore            1
9.95 Crore           1
16 Lac               1
3.99 Crore           1
64.45 Lac            1
86.92 Lac            1
2.86 Crore           1
7.4 Crore            1
3.78 Crore           1
29.5 Lac             1
3.87 Crore           1
94.99 Lac            1
88.4 Lac             1
37.1 Lac             1
9 Crore              1
57 Lac               1
3.72 Crore           1
19 Lac               1
95.5 Lac             1
70.85 Lac            1
7.52 Crore           1
40.3 Lac             1
96.07 Lac            1
32.5 Lac             1
2.96 Crore           1
1.53 Crore           1
26.9 Lac             1
26.5 Lac             1
73.53 Lac            1
89.77 Lac            1
62.5 Lac             1
Name: count, dtype: int64

In [ ]:
df = df[df['price'] != 'Price on Request']

In [ ]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,45 Lac,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,50 Lac,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,40 Lac,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47 Crore,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,70 Lac,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [ ]:
df['price'].dtype

dtype('O')

In [ ]:
# def treat_price(x):
#   if type(x) == float:
#     return x
#   else:
#     if x[1] == 'Lac':
#       return round(float(x[0])/100,2)
#     else:
#       return round(float(x[0]),2)

In [ ]:
# df['price'] = df['price'].str.split(' ').apply(treat_price)

In [ ]:
print(df['price'].value_counts().head(30))

price
1.25 Crore    79
1.1 Crore     61
1.4 Crore     60
1.2 Crore     59
1.5 Crore     59
90 Lac        58
1.3 Crore     57
95 Lac        53
2 Crore       51
1.75 Crore    47
1 Crore       46
1.6 Crore     43
1.35 Crore    41
1.9 Crore     40
1.55 Crore    40
75 Lac        38
1.65 Crore    38
1.8 Crore     37
1.7 Crore     37
80 Lac        36
2.2 Crore     34
1.15 Crore    33
50 Lac        33
1.45 Crore    31
85 Lac        31
1.05 Crore    30
2.5 Crore     29
60 Lac        29
40 Lac        29
2.1 Crore     26
Name: count, dtype: int64

In [ ]:
def treat_price(x):
    if pd.isna(x):
        return None

    x = str(x).strip().split()

    if len(x) < 2:
        return None

    value = float(x[0])

    if x[1] == 'Lac':
        return round(value / 100, 4)
    elif x[1] == 'Crore':
        return value
    else:
        return None

In [ ]:
df = df[df['price'] != 'Price on Request']

df['price'] = df['price'].apply(treat_price)

In [ ]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,"₹ 5,000/sq.ft.",Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,"₹ 7,692/sq.ft.",Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,"₹ 6,722/sq.ft.",Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,"₹ 12,250/sq.ft.",Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,"₹ 5,204/sq.ft.",Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [ ]:
df.sample(3)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
1238,3 BHK Flat in Sector 37C Gurgaon,corona optus,1.25,"₹ 7,175/sq.ft.",Super Built up area 1735(161.19 sq.m.)Carpet a...,3 Bedrooms,3 Bathrooms,3 Balconies,Study Room,"Sector 37C Gurgaon, Gurgaon, Haryana",2nd of 10 Floors,North-West,1 to 5 Year Old,"['The Esplanade Mall', 'Gurugram Road', 'Delhi...",This 3 bhk apartment is available for sale in ...,NaN,"['Feng Shui / Vaastu Compliant', 'Security / F...","['Green Area5 out of 5', 'Construction4 out of..."
2999,3 BHK Flat in Sector 107 Gurgaon,m3m woodshire,1.40,"₹ 5,929/sq.ft.",Super Built up area 2361(219.34 sq.m.),3 Bedrooms,4 Bathrooms,No Balcony,NaN,"A02/101 2361sq Ft, Sector 107 Gurgaon, Gurgaon...",1st of 14 Floors,East,0 to 1 Year Old,NaN,Looking for a good 3 bhk apartment in sector 1...,"['1 Light', 'No AC', 'No Bed', 'No Chimney', '...","['Power Back-up', 'Intercom Facility', 'Lift(s...","['Safety1 out of 5', 'Lifestyle2 out of 5', 'E..."
1976,3 BHK Flat in Sector 92 Gurgaon,sare crescent parc,0.80,"₹ 6,033/sq.ft.",Carpet area: 1326 (123.19 sq.m.),3 Bedrooms,2 Bathrooms,2 Balconies,NaN,"3rd Floor, Sector 92 Gurgaon, Gurgaon, Haryana",3rd of 15 Floors,North-East,1 to 5 Year Old,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...","Ready to move property with spacious room, bal...","['1 Fan', '1 Geyser', '1 Light', '1 AC', '1 Ch...","['Intercom Facility', 'Lift(s)', 'Park']","['Green Area4 out of 5', 'Construction4 out of..."

In [ ]:
# price_per_sqft
df['price_per_sqft'].value_counts()

price_per_sqft
₹ 10,000/sq.ft.     19
₹ 12,500/sq.ft.     16
₹ 8,000/sq.ft.      16
₹ 6,666/sq.ft.      13
₹ 5,000/sq.ft.      13
₹ 7,500/sq.ft.      12
₹ 8,333/sq.ft.      12
₹ 6,000/sq.ft.      11
₹ 8,461/sq.ft.       9
₹ 12,000/sq.ft.      8
₹ 7,000/sq.ft.       8
₹ 9,000/sq.ft.       7
₹ 5,500/sq.ft.       6
₹ 8,928/sq.ft.       6
₹ 11,500/sq.ft.      6
₹ 9,230/sq.ft.       6
₹ 6,578/sq.ft.       6
₹ 11,111/sq.ft.      6
₹ 4,615/sq.ft.       5
₹ 5,556/sq.ft.       5
₹ 7,407/sq.ft.       5
₹ 16,000/sq.ft.      5
₹ 7,641/sq.ft.       5
₹ 7,692/sq.ft.       5
₹ 4,444/sq.ft.       5
₹ 8,888/sq.ft.       5
₹ 14,242/sq.ft.      5
₹ 6,500/sq.ft.       5
₹ 8,571/sq.ft.       5
₹ 8,205/sq.ft.       5
₹ 5,384/sq.ft.       5
₹ 10,714/sq.ft.      5
₹ 4,666/sq.ft.       5
₹ 7,142/sq.ft.       5
₹ 11,428/sq.ft.      5
₹ 5,600/sq.ft.       5
₹ 16,666/sq.ft.      4
₹ 4,814/sq.ft.       4
₹ 7,812/sq.ft.       4
₹ 8,474/sq.ft.       4
₹ 5,660/sq.ft.       4
₹ 7,272/sq.ft.       4
₹ 8,500/sq.ft.       4
₹ 9,090/sq.ft.       4
₹ 13,636/sq.ft.      4
₹ 7,317/sq.ft.       4
₹ 8,445/sq.ft.       4
₹ 8,787/sq.ft.       4
₹ 9,822/sq.ft.       4
₹ 7,250/sq.ft.       4
₹ 8,163/sq.ft.       4
₹ 8,484/sq.ft.       4
₹ 14,418/sq.ft.      4
₹ 15,384/sq.ft.      4
₹ 4,854/sq.ft.       4
₹ 8,358/sq.ft.       4
₹ 6,735/sq.ft.       4
₹ 9,210/sq.ft.       4
₹ 10,416/sq.ft.      4
₹ 8,784/sq.ft.       4
₹ 4,500/sq.ft.       4
₹ 13,913/sq.ft.      4
₹ 7,496/sq.ft.       4
₹ 6,250/sq.ft.       4
₹ 8,108/sq.ft.       4
₹ 8,432/sq.ft.       4
₹ 4,687/sq.ft.       4
₹ 8,043/sq.ft.       4
₹ 15,000/sq.ft.      4
₹ 10,383/sq.ft.      4
₹ 13,750/sq.ft.      4
₹ 8,139/sq.ft.       4
₹ 11,666/sq.ft.      4
₹ 8,148/sq.ft.       3
₹ 5,856/sq.ft.       3
₹ 16,470/sq.ft.      3
₹ 8,750/sq.ft.       3
₹ 13,392/sq.ft.      3
₹ 8,389/sq.ft.       3
₹ 8,532/sq.ft.       3
₹ 7,586/sq.ft.       3
₹ 9,011/sq.ft.       3
₹ 7,179/sq.ft.       3
₹ 8,400/sq.ft.       3
₹ 10,638/sq.ft.      3
₹ 9,972/sq.ft.       3
₹ 6,086/sq.ft.       3
₹ 7,541/sq.ft.       3
₹ 7,954/sq.ft.       3
₹ 5,325/sq.ft.       3
₹ 11,000/sq.ft.      3
₹ 5,397/sq.ft.       3
₹ 6,470/sq.ft.       3
₹ 7,083/sq.ft.       3
₹ 11,363/sq.ft.      3
₹ 8,080/sq.ft.       3
₹ 7,150/sq.ft.       3
₹ 6,421/sq.ft.       3
₹ 14,430/sq.ft.      3
₹ 7,302/sq.ft.       3
₹ 8,222/sq.ft.       3
₹ 6,818/sq.ft.       3
₹ 8,078/sq.ft.       3
₹ 6,387/sq.ft.       3
₹ 5,833/sq.ft.       3
₹ 14,254/sq.ft.      3
₹ 9,615/sq.ft.       3
₹ 8,606/sq.ft.       3
₹ 5,238/sq.ft.       3
₹ 8,215/sq.ft.       3
₹ 9,900/sq.ft.       3
₹ 9,473/sq.ft.       3
₹ 5,735/sq.ft.       3
₹ 6,921/sq.ft.       3
₹ 16,969/sq.ft.      3
₹ 10,555/sq.ft.      3
₹ 8,620/sq.ft.       3
₹ 8,181/sq.ft.       3
₹ 9,500/sq.ft.       3
₹ 7,865/sq.ft.       3
₹ 7,400/sq.ft.       3
₹ 13,000/sq.ft.      3
₹ 7,467/sq.ft.       3
₹ 6,404/sq.ft.       3
₹ 10,500/sq.ft.      3
₹ 6,644/sq.ft.       3
₹ 4,800/sq.ft.       3
₹ 10,204/sq.ft.      3
₹ 4,513/sq.ft.       3
₹ 4,210/sq.ft.       3
₹ 7,549/sq.ft.       3
₹ 6,667/sq.ft.       3
₹ 13,870/sq.ft.      3
₹ 14,000/sq.ft.      3
₹ 8,450/sq.ft.       3
₹ 8,886/sq.ft.       3
₹ 6,542/sq.ft.       3
₹ 7,056/sq.ft.       3
₹ 5,319/sq.ft.       3
₹ 10,139/sq.ft.      3
₹ 9,904/sq.ft.       3
₹ 4,105/sq.ft.       3
₹ 8,604/sq.ft.       3
₹ 6,476/sq.ft.       3
₹ 7,750/sq.ft.       3
₹ 5,878/sq.ft.       3
₹ 7,948/sq.ft.       3
₹ 5,555/sq.ft.       3
₹ 19,747/sq.ft.      2
₹ 6,313/sq.ft.       2
₹ 6,825/sq.ft.       2
₹ 6,254/sq.ft.       2
₹ 5,820/sq.ft.       2
₹ 7,014/sq.ft.       2
₹ 5,714/sq.ft.       2
₹ 15,151/sq.ft.      2
₹ 6,200/sq.ft.       2
₹ 7,846/sq.ft.       2
₹ 7,297/sq.ft.       2
₹ 13,108/sq.ft.      2
₹ 15,551/sq.ft.      2
₹ 15,416/sq.ft.      2
₹ 9,743/sq.ft.       2
₹ 5,839/sq.ft.       2
₹ 11,765/sq.ft.      2
₹ 17,039/sq.ft.      2
₹ 8,846/sq.ft.       2
₹ 9,146/sq.ft.       2
₹ 7,751/sq.ft.       2
₹ 9,025/sq.ft.       2
₹ 6,967/sq.ft.       2
₹ 7,627/sq.ft.       2
₹ 6,506/sq.ft.       2
₹ 19,882/sq.ft.      2
₹ 9,791/sq.ft.       2
₹ 9,620/sq.ft.       2
₹ 7,097/sq.ft.       2
₹ 7,490/sq.ft.       2
₹ 6,076/sq.ft.       2
₹ 6,111/sq.ft.       2
₹ 6,178/sq.ft.       2
₹ 9,135/sq.ft.       2
₹ 7,796/sq.ft.       2
₹ 10,476/sq.ft.      2
₹ 7,200/sq.ft.       2
₹ 5,882/sq.ft.       2
₹ 13,500/sq.ft.      2
₹ 9,909/sq.ft.       2
₹ 9,876/sq.ft.       2
₹ 4,820/sq.ft.       2
₹ 12,777/sq.ft.      2
₹ 8,670/sq.ft.       2
₹ 8,159/sq.ft.       2
₹ 7,058/sq.ft.       2
₹ 11,715/sq.ft.      2
₹ 7,174/sq.ft.       2
₹ 6,938/sq.ft.       2
₹ 5,671/sq.ft.       2
₹ 6,789/sq.ft.       2
₹ 8,504/sq.ft.       2
₹ 9,166/sq.ft.       2
₹ 9,978/sq.ft.       2
₹ 3,695/sq.ft.       2
₹ 11,992/sq.ft.      2
₹ 5,658/sq.ft.       2
₹ 6,217/sq.ft.       2
₹ 9,062/sq.ft.       2
₹ 9,449/sq.ft.       2
₹ 8,053/sq.ft.       2
₹ 7,585/sq.ft.       2
₹ 10,601/sq.ft.      2
₹ 18,000/sq.ft.      2
₹ 7,758/sq.ft.       2
₹ 7,863/sq.ft.       2
₹ 11,250/sq.ft.      2
₹ 4,307/sq.ft.       2
₹ 8,974/sq.ft.       2
₹ 6,985/sq.ft.       2
₹ 11,724/sq.ft.      2
₹ 6,024/sq.ft.       2
₹ 6,061/sq.ft.       2
₹ 6,429/sq.ft.       2
₹ 6,377/sq.ft.       2
₹ 10,531/sq.ft.      2
₹ 5,038/sq.ft.       2
₹ 5,797/sq.ft.       2
₹ 9,677/sq.ft.       2
₹ 8,517/sq.ft.       2
₹ 9,452/sq.ft.       2
₹ 6,927/sq.ft.       2
₹ 6,190/sq.ft.       2
₹ 6,206/sq.ft.       2
₹ 15,294/sq.ft.      2
₹ 5,128/sq.ft.       2
₹ 14,785/sq.ft.      2
₹ 10,018/sq.ft.      2
₹ 8,433/sq.ft.       2
₹ 20,687/sq.ft.      2
₹ 12,212/sq.ft.      2
₹ 15,500/sq.ft.      2
₹ 5,150/sq.ft.       2
₹ 6,428/sq.ft.       2
₹ 5,100/sq.ft.       2
₹ 5,517/sq.ft.       2
₹ 8,618/sq.ft.       2
₹ 6,686/sq.ft.       2
₹ 8,972/sq.ft.       2
₹ 5,111/sq.ft.       2
₹ 5,786/sq.ft.       2
₹ 9,797/sq.ft.       2
₹ 9,922/sq.ft.       2
₹ 7,359/sq.ft.       2
₹ 8,720/sq.ft.       2
₹ 6,318/sq.ft.       2
₹ 11,627/sq.ft.      2
₹ 6,569/sq.ft.       2
₹ 11,529/sq.ft.      2
₹ 41,245/sq.ft.      2
₹ 9,851/sq.ft.       2
₹ 8,075/sq.ft.       2
₹ 7,727/sq.ft.       2
₹ 15,998/sq.ft.      2
₹ 7,574/sq.ft.       2
₹ 5,521/sq.ft.       2
₹ 6,812/sq.ft.       2
₹ 8,609/sq.ft.       2
₹ 8,524/sq.ft.       2
₹ 9,600/sq.ft.       2
₹ 9,286/sq.ft.       2
₹ 6,510/sq.ft.       2
₹ 7,225/sq.ft.       2
₹ 11,700/sq.ft.      2
₹ 6,551/sq.ft.       2
₹ 6,983/sq.ft.       2
₹ 6,739/sq.ft.       2
₹ 6,325/sq.ft.       2
₹ 10,603/sq.ft.      2
₹ 7,391/sq.ft.       2
₹ 16,960/sq.ft.      2
₹ 11,516/sq.ft.      2
₹ 9,672/sq.ft.       2
₹ 8,310/sq.ft.       2
₹ 7,530/sq.ft.       2
₹ 8,006/sq.ft.       2
₹ 14,257/sq.ft.      2
₹ 9,333/sq.ft.       2
₹ 14,214/sq.ft.      2
₹ 7,248/sq.ft.       2
₹ 8,600/sq.ft.       2
₹ 14,545/sq.ft.      2
₹ 5,424/sq.ft.       2
₹ 10,599/sq.ft.      2
₹ 6,338/sq.ft.       2
₹ 8,035/sq.ft.       2
₹ 8,036/sq.ft.       2
₹ 8,611/sq.ft.       2
₹ 13,769/sq.ft.      2
₹ 12,782/sq.ft.      2
₹ 8,072/sq.ft.       2
₹ 14,583/sq.ft.      2
₹ 4,000/sq.ft.       2
₹ 5,899/sq.ft.       2
₹ 11,333/sq.ft.      2
₹ 9,259/sq.ft.       2
₹ 10,384/sq.ft.      2
₹ 10,526/sq.ft.      2
₹ 8,582/sq.ft.       2
₹ 14,478/sq.ft.      2
₹ 17,619/sq.ft.      2
₹ 8,206/sq.ft.       2
₹ 6,597/sq.ft.       2
₹ 18,181/sq.ft.      2
₹ 4,271/sq.ft.       2
₹ 18,271/sq.ft.      2
₹ 8,252/sq.ft.       2
₹ 16,985/sq.ft.      2
₹ 6,422/sq.ft.       2
₹ 4,909/sq.ft.       2
₹ 8,897/sq.ft.       2
₹ 4,327/sq.ft.       2
₹ 9,027/sq.ft.       2
₹ 6,420/sq.ft.       2
₹ 5,405/sq.ft.       2
₹ 11,755/sq.ft.      2
₹ 7,782/sq.ft.       2
₹ 7,780/sq.ft.       2
₹ 6,593/sq.ft.       2
₹ 10,370/sq.ft.      2
₹ 9,182/sq.ft.       2
₹ 4,651/sq.ft.       2
₹ 14,800/sq.ft.      2
₹ 8,521/sq.ft.       2
₹ 11,028/sq.ft.      2
₹ 6,134/sq.ft.       2
₹ 13,281/sq.ft.      2
₹ 16,858/sq.ft.      2
₹ 8,166/sq.ft.       2
₹ 7,631/sq.ft.       2
₹ 11,726/sq.ft.      2
₹ 9,263/sq.ft.       2
₹ 6,189/sq.ft.       2
₹ 58/sq.ft.          2
₹ 5,463/sq.ft.       2
₹ 7,825/sq.ft.       2
₹ 6,373/sq.ft.       2
₹ 6,382/sq.ft.       2
₹ 14,683/sq.ft.      2
₹ 14,303/sq.ft.      2
₹ 5,177/sq.ft.       2
₹ 8,305/sq.ft.       2
₹ 13,224/sq.ft.      2
₹ 6,588/sq.ft.       2
₹ 8,756/sq.ft.       2
₹ 9,482/sq.ft.       2
₹ 5,599/sq.ft.       2
₹ 4,745/sq.ft.       2
₹ 9,022/sq.ft.       2
₹ 12,012/sq.ft.      2
₹ 7,185/sq.ft.       2
₹ 6,243/sq.ft.       2
₹ 5,681/sq.ft.       2
₹ 7,716/sq.ft.       2
₹ 5,982/sq.ft.       2
₹ 8,024/sq.ft.       2
₹ 6,896/sq.ft.       2
₹ 6,153/sq.ft.       2
₹ 9,306/sq.ft.       2
₹ 7,884/sq.ft.       2
₹ 13,383/sq.ft.      2
₹ 5,980/sq.ft.       2
₹ 5,828/sq.ft.       2
₹ 8,518/sq.ft.       2
₹ 8,457/sq.ft.       2
₹ 5,454/sq.ft.       2
₹ 8,424/sq.ft.       2
₹ 11,505/sq.ft.      2
₹ 7,987/sq.ft.       2
₹ 8,412/sq.ft.       2
₹ 21,538/sq.ft.      2
₹ 9,854/sq.ft.       2
₹ 11,125/sq.ft.      2
₹ 13,991/sq.ft.      2
₹ 8,279/sq.ft.       2
₹ 200,000/sq.ft.     2
₹ 9,589/sq.ft.       2
₹ 5,564/sq.ft.       2
₹ 6,406/sq.ft.       2
₹ 8,410/sq.ft.       2
₹ 10,516/sq.ft.      2
₹ 10,936/sq.ft.      2
₹ 7,945/sq.ft.       2
₹ 6,049/sq.ft.       2
₹ 6,839/sq.ft.       2
₹ 16,747/sq.ft.      2
₹ 8,290/sq.ft.       2
₹ 8,519/sq.ft.       2
₹ 3,911/sq.ft.       2
₹ 6,333/sq.ft.       2
₹ 6,315/sq.ft.       2
₹ 6,053/sq.ft.       2
₹ 4,856/sq.ft.       2
₹ 5,056/sq.ft.       2
₹ 14,237/sq.ft.      2
₹ 5,641/sq.ft.       2
₹ 16,363/sq.ft.      2
₹ 13,709/sq.ft.      2
₹ 6,679/sq.ft.       2
₹ 6,141/sq.ft.       2
₹ 8,376/sq.ft.       2
₹ 6,538/sq.ft.       2
₹ 6,950/sq.ft.       2
₹ 12,022/sq.ft.      2
₹ 13,270/sq.ft.      2
₹ 19,767/sq.ft.      2
₹ 11,336/sq.ft.      2
₹ 7,908/sq.ft.       2
₹ 9,007/sq.ft.       2
₹ 8,733/sq.ft.       2
₹ 8,835/sq.ft.       2
₹ 4,761/sq.ft.       2
₹ 6,465/sq.ft.       2
₹ 8,536/sq.ft.       2
₹ 19,000/sq.ft.      2
₹ 7,396/sq.ft.       2
₹ 15,263/sq.ft.      2
₹ 6,571/sq.ft.       2
₹ 6,774/sq.ft.       2
₹ 4,857/sq.ft.       2
₹ 8,632/sq.ft.       2
₹ 8,324/sq.ft.       2
₹ 14,285/sq.ft.      2
₹ 6,353/sq.ft.       2
₹ 14,615/sq.ft.      2
₹ 7,610/sq.ft.       2
₹ 7,350/sq.ft.       2
₹ 9,074/sq.ft.       2
₹ 7,765/sq.ft.       2
₹ 6,402/sq.ft.       2
₹ 9,020/sq.ft.       2
₹ 10,553/sq.ft.      2
₹ 9,742/sq.ft.       2
₹ 8,411/sq.ft.       2
₹ 9,950/sq.ft.       2
₹ 10,237/sq.ft.      2
₹ 12,444/sq.ft.      2
₹ 5,896/sq.ft.       2
₹ 8,834/sq.ft.       2
₹ 13,076/sq.ft.      2
₹ 6,987/sq.ft.       2
₹ 11,412/sq.ft.      2
₹ 5,744/sq.ft.       2
₹ 8,294/sq.ft.       2
₹ 3,477/sq.ft.       2
₹ 8,814/sq.ft.       2
₹ 8,031/sq.ft.       2
₹ 9,550/sq.ft.       2
₹ 8,237/sq.ft.       2
₹ 15,454/sq.ft.      2
₹ 7,878/sq.ft.       2
₹ 9,105/sq.ft.       2
₹ 10,699/sq.ft.      2
₹ 6,647/sq.ft.       2
₹ 9,642/sq.ft.       2
₹ 11,694/sq.ft.      2
₹ 6,029/sq.ft.       2
₹ 10,545/sq.ft.      2
₹ 5,513/sq.ft.       2
₹ 9,139/sq.ft.       2
₹ 11,727/sq.ft.      2
₹ 10,489/sq.ft.      2
₹ 15,195/sq.ft.      2
₹ 5,929/sq.ft.       2
₹ 8,283/sq.ft.       2
₹ 5,725/sq.ft.       2
₹ 9,433/sq.ft.       2
₹ 10,651/sq.ft.      2
₹ 5,808/sq.ft.       2
₹ 4,080/sq.ft.       2
₹ 8,947/sq.ft.       2
₹ 9,128/sq.ft.       2
₹ 11,574/sq.ft.      2
₹ 7,449/sq.ft.       2
₹ 5,588/sq.ft.       2
₹ 6,692/sq.ft.       2
₹ 5,252/sq.ft.       2
₹ 13,928/sq.ft.      2
₹ 7,850/sq.ft.       2
₹ 7,817/sq.ft.       2
₹ 9,565/sq.ft.       2
₹ 13,343/sq.ft.      2
₹ 5,189/sq.ft.       2
₹ 6,722/sq.ft.       2
₹ 12,250/sq.ft.      2
₹ 13,333/sq.ft.      2
₹ 6,859/sq.ft.       2
₹ 5,528/sq.ft.       2
₹ 8,903/sq.ft.       2
₹ 6,811/sq.ft.       2
₹ 6,209/sq.ft.       2
₹ 5,284/sq.ft.       2
₹ 5,614/sq.ft.       2
₹ 6,616/sq.ft.       2
₹ 6,702/sq.ft.       2
₹ 5,291/sq.ft.       2
₹ 10,596/sq.ft.      2
₹ 10,666/sq.ft.      2
₹ 5,825/sq.ft.       2
₹ 8,100/sq.ft.       2
₹ 6,455/sq.ft.       2
₹ 5,683/sq.ft.       2
₹ 18,518/sq.ft.      2
₹ 12,222/sq.ft.      2
₹ 7,608/sq.ft.       2
₹ 6,655/sq.ft.       2
₹ 5,674/sq.ft.       2
₹ 7,857/sq.ft.       2
₹ 8,453/sq.ft.       2
₹ 13,430/sq.ft.      2
₹ 16,608/sq.ft.      2
₹ 5,649/sq.ft.       2
₹ 7,223/sq.ft.       2
₹ 13,513/sq.ft.      1
₹ 5,204/sq.ft.       1
₹ 6,269/sq.ft.       1
₹ 7,860/sq.ft.       1
₹ 16,885/sq.ft.      1
₹ 9,767/sq.ft.       1
₹ 5,587/sq.ft.       1
₹ 5,789/sq.ft.       1
₹ 50,000/sq.ft.      1
₹ 5,367/sq.ft.       1
₹ 4,596/sq.ft.       1
₹ 4,033/sq.ft.       1
₹ 4,879/sq.ft.       1
₹ 6,505/sq.ft.       1
₹ 6,761/sq.ft.       1
₹ 4,700/sq.ft.       1
₹ 12,700/sq.ft.      1
₹ 5,257/sq.ft.       1
₹ 6,064/sq.ft.       1
₹ 17,548/sq.ft.      1
₹ 5,576/sq.ft.       1
₹ 4,657/sq.ft.       1
₹ 7,079/sq.ft.       1
₹ 14,623/sq.ft.      1
₹ 12,110/sq.ft.      1
₹ 11,739/sq.ft.      1
₹ 14,074/sq.ft.      1
₹ 7,146/sq.ft.       1
₹ 12,400/sq.ft.      1
₹ 13,875/sq.ft.      1
₹ 13,846/sq.ft.      1
₹ 6,708/sq.ft.       1
₹ 6,580/sq.ft.       1
₹ 6,514/sq.ft.       1
₹ 13,929/sq.ft.      1
₹ 17,285/sq.ft.      1
₹ 6,819/sq.ft.       1
₹ 9,133/sq.ft.       1
₹ 35,222/sq.ft.      1
₹ 14,557/sq.ft.      1
₹ 13,878/sq.ft.      1
₹ 13,888/sq.ft.      1
₹ 9,036/sq.ft.       1
₹ 9,980/sq.ft.       1
₹ 7,065/sq.ft.       1
₹ 5,499/sq.ft.       1
₹ 4,864/sq.ft.       1
₹ 13,528/sq.ft.      1
₹ 9,622/sq.ft.       1
₹ 9,051/sq.ft.       1
₹ 3,935/sq.ft.       1
₹ 4,022/sq.ft.       1
₹ 7,437/sq.ft.       1
₹ 21,013/sq.ft.      1
₹ 6,523/sq.ft.       1
₹ 8,759/sq.ft.       1
₹ 14,983/sq.ft.      1
₹ 11,914/sq.ft.      1
₹ 24,211/sq.ft.      1
₹ 20,533/sq.ft.      1
₹ 15,469/sq.ft.      1
₹ 10,761/sq.ft.      1
₹ 10,994/sq.ft.      1
₹ 12,144/sq.ft.      1
₹ 12,127/sq.ft.      1
₹ 14,536/sq.ft.      1
₹ 11,052/sq.ft.      1
₹ 10,953/sq.ft.      1
₹ 9,117/sq.ft.       1
₹ 9,387/sq.ft.       1
₹ 12,325/sq.ft.      1
₹ 10,365/sq.ft.      1
₹ 8,242/sq.ft.       1
₹ 12,169/sq.ft.      1
₹ 17,484/sq.ft.      1
₹ 7,403/sq.ft.       1
₹ 35,483/sq.ft.      1
₹ 6,215/sq.ft.       1
₹ 13,725/sq.ft.      1
₹ 6,953/sq.ft.       1
₹ 8,724/sq.ft.       1
₹ 11,860/sq.ft.      1
₹ 9,266/sq.ft.       1
₹ 10,334/sq.ft.      1
₹ 16,580/sq.ft.      1
₹ 16,750/sq.ft.      1
₹ 8,839/sq.ft.       1
₹ 4,836/sq.ft.       1
₹ 5,004/sq.ft.       1
₹ 13,678/sq.ft.      1
₹ 12,599/sq.ft.      1
₹ 11,358/sq.ft.      1
₹ 14,987/sq.ft.      1
₹ 6,060/sq.ft.       1
₹ 8,516/sq.ft.       1
₹ 10,028/sq.ft.      1
₹ 15,007/sq.ft.      1
₹ 9,203/sq.ft.       1
₹ 10,178/sq.ft.      1
₹ 4,531/sq.ft.       1
₹ 5,859/sq.ft.       1
₹ 14,068/sq.ft.      1
₹ 7,789/sq.ft.       1
₹ 8,204/sq.ft.       1
₹ 8,825/sq.ft.       1
₹ 9,850/sq.ft.       1
₹ 10,224/sq.ft.      1
₹ 10,262/sq.ft.      1
₹ 13,671/sq.ft.      1
₹ 14,727/sq.ft.      1
₹ 8,679/sq.ft.       1
₹ 14,090/sq.ft.      1
₹ 6,052/sq.ft.       1
₹ 12,571/sq.ft.      1
₹ 8,172/sq.ft.       1
₹ 10,080/sq.ft.      1
₹ 10,461/sq.ft.      1
₹ 8,646/sq.ft.       1
₹ 10,595/sq.ft.      1
₹ 6,310/sq.ft.       1
₹ 8,922/sq.ft.       1
₹ 5,490/sq.ft.       1
₹ 6,242/sq.ft.       1
₹ 11,451/sq.ft.      1
₹ 8,998/sq.ft.       1
₹ 7,096/sq.ft.       1
₹ 14,179/sq.ft.      1
₹ 9,238/sq.ft.       1
₹ 5,930/sq.ft.       1
₹ 8,062/sq.ft.       1
₹ 6,002/sq.ft.       1
₹ 6,846/sq.ft.       1
₹ 6,286/sq.ft.       1
₹ 15,685/sq.ft.      1
₹ 13,758/sq.ft.      1
₹ 21,577/sq.ft.      1
₹ 16,266/sq.ft.      1
₹ 12,658/sq.ft.      1
₹ 13,580/sq.ft.      1
₹ 20,388/sq.ft.      1
₹ 12,846/sq.ft.      1
₹ 14,843/sq.ft.      1
₹ 6,852/sq.ft.       1
₹ 5,762/sq.ft.       1
₹ 15,531/sq.ft.      1
₹ 12,484/sq.ft.      1
₹ 3,953/sq.ft.       1
₹ 4,308/sq.ft.       1
₹ 6,265/sq.ft.       1
₹ 7,116/sq.ft.       1
₹ 10,162/sq.ft.      1
₹ 4,355/sq.ft.       1
₹ 4,370/sq.ft.       1
₹ 12,190/sq.ft.      1
₹ 13,253/sq.ft.      1
₹ 12,152/sq.ft.      1
₹ 15,185/sq.ft.      1
₹ 5,973/sq.ft.       1
₹ 6,453/sq.ft.       1
₹ 7,230/sq.ft.       1
₹ 6,585/sq.ft.       1
₹ 11,686/sq.ft.      1
₹ 6,801/sq.ft.       1
₹ 7,525/sq.ft.       1
₹ 11,218/sq.ft.      1
₹ 8,270/sq.ft.       1
₹ 11,713/sq.ft.      1
₹ 12,372/sq.ft.      1
₹ 10,529/sq.ft.      1
₹ 10,147/sq.ft.      1
₹ 6,227/sq.ft.       1
₹ 10,727/sq.ft.      1
₹ 5,942/sq.ft.       1
₹ 10,037/sq.ft.      1
₹ 8,395/sq.ft.       1
₹ 5,597/sq.ft.       1
₹ 8,916/sq.ft.       1
₹ 8,875/sq.ft.       1
₹ 5,207/sq.ft.       1
₹ 19,174/sq.ft.      1
₹ 7,590/sq.ft.       1
₹ 5,418/sq.ft.       1
₹ 7,734/sq.ft.       1
₹ 4,528/sq.ft.       1
₹ 6,961/sq.ft.       1
₹ 7,646/sq.ft.       1
₹ 10,174/sq.ft.      1
₹ 14,177/sq.ft.      1
₹ 5,867/sq.ft.       1
₹ 5,717/sq.ft.       1
₹ 10,841/sq.ft.      1
₹ 11,174/sq.ft.      1
₹ 10,443/sq.ft.      1
₹ 6,625/sq.ft.       1
₹ 8,793/sq.ft.       1
₹ 13,352/sq.ft.      1
₹ 15,561/sq.ft.      1
₹ 6,530/sq.ft.       1
₹ 11,817/sq.ft.      1
₹ 8,708/sq.ft.       1
₹ 9,512/sq.ft.       1
₹ 7,380/sq.ft.       1
₹ 18,126/sq.ft.      1
₹ 7,180/sq.ft.       1
₹ 7,072/sq.ft.       1
₹ 12,047/sq.ft.      1
₹ 9,039/sq.ft.       1
₹ 8,623/sq.ft.       1
₹ 8,704/sq.ft.       1
₹ 9,365/sq.ft.       1
₹ 10,041/sq.ft.      1
₹ 9,627/sq.ft.       1
₹ 10,786/sq.ft.      1
₹ 13,571/sq.ft.      1
₹ 8,580/sq.ft.       1
₹ 14,563/sq.ft.      1
₹ 15,514/sq.ft.      1
₹ 9,528/sq.ft.       1
₹ 6,826/sq.ft.       1
₹ 12,788/sq.ft.      1
₹ 10,567/sq.ft.      1
₹ 11,470/sq.ft.      1
₹ 11,204/sq.ft.      1
₹ 11,294/sq.ft.      1
₹ 15,906/sq.ft.      1
₹ 3,309/sq.ft.       1
₹ 10,954/sq.ft.      1
₹ 9,497/sq.ft.       1
₹ 4,746/sq.ft.       1
₹ 9,052/sq.ft.       1
₹ 8,023/sq.ft.       1
₹ 8,553/sq.ft.       1
₹ 7,208/sq.ft.       1
₹ 7,443/sq.ft.       1
₹ 9,030/sq.ft.       1
₹ 6,424/sq.ft.       1
₹ 11,489/sq.ft.      1
₹ 9,655/sq.ft.       1
₹ 9,169/sq.ft.       1
₹ 10,799/sq.ft.      1
₹ 12,589/sq.ft.      1
₹ 10,853/sq.ft.      1
₹ 5,531/sq.ft.       1
₹ 6,019/sq.ft.       1
₹ 6,104/sq.ft.       1
₹ 6,888/sq.ft.       1
₹ 9,212/sq.ft.       1
₹ 6,163/sq.ft.       1
₹ 6,661/sq.ft.       1
₹ 15,160/sq.ft.      1
₹ 12,140/sq.ft.      1
₹ 10,814/sq.ft.      1
₹ 13,790/sq.ft.      1
₹ 6,713/sq.ft.       1
₹ 14,079/sq.ft.      1
₹ 12,235/sq.ft.      1
₹ 7,196/sq.ft.       1
₹ 6,932/sq.ft.       1
₹ 12,178/sq.ft.      1
₹ 9,584/sq.ft.       1
₹ 12,813/sq.ft.      1
₹ 11,764/sq.ft.      1
₹ 16,129/sq.ft.      1
₹ 10,755/sq.ft.      1
₹ 6,851/sq.ft.       1
₹ 8,256/sq.ft.       1
₹ 5,026/sq.ft.       1
₹ 7,636/sq.ft.       1
₹ 7,928/sq.ft.       1
₹ 9,393/sq.ft.       1
₹ 8,813/sq.ft.       1
₹ 10,465/sq.ft.      1
₹ 9,563/sq.ft.       1
₹ 13,589/sq.ft.      1
₹ 10,645/sq.ft.      1
₹ 8,541/sq.ft.       1
₹ 15,418/sq.ft.      1
₹ 4,193/sq.ft.       1
₹ 10,901/sq.ft.      1
₹ 28,101/sq.ft.      1
₹ 8,051/sq.ft.       1
₹ 13,690/sq.ft.      1
₹ 5,788/sq.ft.       1
₹ 13,125/sq.ft.      1
₹ 5,607/sq.ft.       1
₹ 6,609/sq.ft.       1
₹ 8,818/sq.ft.       1
₹ 7,554/sq.ft.       1
₹ 11,233/sq.ft.      1
₹ 6,641/sq.ft.       1
₹ 7,339/sq.ft.       1
₹ 12,134/sq.ft.      1
₹ 7,167/sq.ft.       1
₹ 8,320/sq.ft.       1
₹ 11,438/sq.ft.      1
₹ 4,961/sq.ft.       1
₹ 24,963/sq.ft.      1
₹ 15,510/sq.ft.      1
₹ 14,598/sq.ft.      1
₹ 11,227/sq.ft.      1
₹ 6,975/sq.ft.       1
₹ 5,887/sq.ft.       1
₹ 7,991/sq.ft.       1
₹ 3,152/sq.ft.       1
₹ 14,375/sq.ft.      1
₹ 16,959/sq.ft.      1
₹ 5,422/sq.ft.       1
₹ 12,544/sq.ft.      1
₹ 9,783/sq.ft.       1
₹ 14,950/sq.ft.      1
₹ 7,260/sq.ft.       1
₹ 12,818/sq.ft.      1
₹ 7,392/sq.ft.       1
₹ 12,627/sq.ft.      1
₹ 7,220/sq.ft.       1
₹ 26,790/sq.ft.      1
₹ 21,360/sq.ft.      1
₹ 16,486/sq.ft.      1
₹ 11,121/sq.ft.      1
₹ 5,605/sq.ft.       1
₹ 10,449/sq.ft.      1
₹ 11,050/sq.ft.      1
₹ 10,825/sq.ft.      1
₹ 6,369/sq.ft.       1
₹ 14,040/sq.ft.      1
₹ 7,652/sq.ft.       1
₹ 9,933/sq.ft.       1
₹ 7,904/sq.ft.       1
₹ 5,747/sq.ft.       1
₹ 6,267/sq.ft.       1
₹ 13,837/sq.ft.      1
₹ 11,966/sq.ft.      1
₹ 12,471/sq.ft.      1
₹ 13,318/sq.ft.      1
₹ 12,371/sq.ft.      1
₹ 8,769/sq.ft.       1
₹ 11,868/sq.ft.      1
₹ 12,732/sq.ft.      1
₹ 11,338/sq.ft.      1
₹ 12,533/sq.ft.      1
₹ 5,505/sq.ft.       1
₹ 18,500/sq.ft.      1
₹ 16,050/sq.ft.      1
₹ 6,934/sq.ft.       1
₹ 19,285/sq.ft.      1
₹ 12,622/sq.ft.      1
₹ 6,079/sq.ft.       1

In [ ]:
df['price_per_sqft'] = df['price_per_sqft'].str.split('/').str.get(0).str.replace('₹','').str.replace(',','').str.strip().astype('float')

In [ ]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [ ]:
# areaWithType -> need feature engineering
df['areaWithType'].value_counts()

areaWithType
Super Built up area 1950(181.16 sq.m.)Carpet area: 1161 sq.ft. (107.86 sq.m.)                                                   17
Super Built up area 1350(125.42 sq.m.)                                                                                          17
Super Built up area 1578(146.6 sq.m.)                                                                                           17
Super Built up area 1650(153.29 sq.m.)Carpet area: 1022.58 sq.ft. (95 sq.m.)                                                    15
Super Built up area 2010(186.74 sq.m.)                                                                                          14
Super Built up area 2150(199.74 sq.m.)                                                                                          12
Super Built up area 1950(181.16 sq.m.)                                                                                          11
Carpet area: 1650 (153.29 sq.m.)                                                                                                11
Super Built up area 1920(178.37 sq.m.)                                                                                          10
Carpet area: 1150 (106.84 sq.m.)                                                                                                10
Super Built up area 1650(153.29 sq.m.)                                                                                          10
Super Built up area 1550(144 sq.m.)                                                                                             10
Carpet area: 1450 (134.71 sq.m.)                                                                                                 9
Carpet area: 1350 (125.42 sq.m.)                                                                                                 9
Carpet area: 489 (45.43 sq.m.)                                                                                                   9
Super Built up area 1640(152.36 sq.m.)                                                                                           9
Super Built up area 1828(169.83 sq.m.)                                                                                           9
Super Built up area 1366(126.91 sq.m.)                                                                                           8
Carpet area: 2400 (222.97 sq.m.)                                                                                                 8
Carpet area: 750 (69.68 sq.m.)                                                                                                   8
Super Built up area 1760(163.51 sq.m.)Built Up area: 1186 sq.ft. (110.18 sq.m.)Carpet area: 1130 sq.ft. (104.98 sq.m.)           8
Carpet area: 1950 (181.16 sq.m.)                                                                                                 8
Carpet area: 900 (83.61 sq.m.)                                                                                                   8
Carpet area: 1800 (167.23 sq.m.)                                                                                                 8
Super Built up area 3400(315.87 sq.m.)                                                                                           7
Carpet area: 1600 (148.64 sq.m.)                                                                                                 7
Carpet area: 1300 (120.77 sq.m.)                                                                                                 7
Super Built up area 1415(131.46 sq.m.)                                                                                           7
Super Built up area 1930(179.3 sq.m.)                                                                                            7
Super Built up area 2408(223.71 sq.m.)                                                                                           7
Super Built up area 2200(204.39 sq.m.)                                                                                           7
Carpet area: 2300 (213.68 sq.m.)                                                                                                 7
Carpet area: 1760 (163.51 sq.m.)                                                                                                 7
Super Built up area 2364(219.62 sq.m.)                                                                                           7
Super Built up area 2350(218.32 sq.m.)                                                                                           7
Carpet area: 1103 (102.47 sq.m.)                                                                                                 7
Super Built up area 2100(195.1 sq.m.)                                                                                            7
Super Built up area 1200(111.48 sq.m.)                                                                                           7
Super Built up area 1538(142.88 sq.m.)                                                                                           7
Super Built up area 3150(292.64 sq.m.)                                                                                           6
Super Built up area 2727(253.35 sq.m.)                                                                                           6
Carpet area: 1423 (132.2 sq.m.)                                                                                                  6
Carpet area: 822 (76.37 sq.m.)                                                                                                   6
Carpet area: 700 (65.03 sq.m.)                                                                                                   6
Carpet area: 1326 (123.19 sq.m.)                                                                                                 6
Super Built up area 2812(261.24 sq.m.)                                                                                           6
Super Built up area 1572(146.04 sq.m.)                                                                                           6
Super Built up area 1750(162.58 sq.m.)                                                                                           6
Super Built up area 2215(205.78 sq.m.)                                                                                           6
Super Built up area 1568(145.67 sq.m.)                                                                                           6
Super Built up area 2290(212.75 sq.m.)                                                                                           6
Super Built up area 2000(185.81 sq.m.)                                                                                           5
Super Built up area 1875(174.19 sq.m.)                                                                                           5
Super Built up area 1975(183.48 sq.m.)                                                                                           5
Super Built up area 2149(199.65 sq.m.)                                                                                           5
Carpet area: 645 (59.92 sq.m.)                                                                                                   5
Carpet area: 1975 (183.48 sq.m.)                                                                                                 5
Super Built up area 1480(137.5 sq.m.)                                                                                            5
Super Built up area 1360(126.35 sq.m.)                                                                                           5
Super Built up area 1000(92.9 sq.m.)                                                                                             5
Super Built up area 1245(115.66 sq.m.)                                                                                           5
Super Built up area 1565(145.39 sq.m.)                                                                                           5
Carpet area: 1050 (97.55 sq.m.)                                                                                                  5
Super Built up area 2025(188.13 sq.m.)                                                                                           5
Super Built up area 1457(135.36 sq.m.)Carpet area: 849 sq.ft. (78.87 sq.m.)                                                      5
Super Built up area 1215(112.88 sq.m.)                                                                                           5
Carpet area: 2000 (185.81 sq.m.)                                                                                                 5
Super Built up area 1960(182.09 sq.m.)                                                                                           5
Built Up area: 700 (65.03 sq.m.)                                                                                                 5
Super Built up area 1700(157.94 sq.m.)                                                                                           5
Super Built up area 1970(183.02 sq.m.)                                                                                           5
Carpet area: 850 (78.97 sq.m.)                                                                                                   5
Super Built up area 1435(133.32 sq.m.)                                                                                           5
Super Built up area 2812(261.24 sq.m.)Built Up area: 2600 sq.ft. (241.55 sq.m.)Carpet area: 2400 sq.ft. (222.97 sq.m.)           5
Carpet area: 450 (41.81 sq.m.)                                                                                                   5
Carpet area: 600 (55.74 sq.m.)                                                                                                   5
Super Built up area 1997(185.53 sq.m.)                                                                                           5
Super Built up area 1850(171.87 sq.m.)                                                                                           5
Carpet area: 1200 (111.48 sq.m.)                                                                                                 5
Super Built up area 2545(236.44 sq.m.)                                                                                           4
Super Built up area 1365(126.81 sq.m.)                                                                                           4
Super Built up area 1942(180.42 sq.m.)                                                                                           4
Carpet area: 800 (74.32 sq.m.)                                                                                                   4
Built Up area: 1350 (125.42 sq.m.)                                                                                               4
Carpet area: 1225 (113.81 sq.m.)                                                                                                 4
Super Built up area 1727(160.44 sq.m.)Carpet area: 1017 sq.ft. (94.48 sq.m.)                                                     4
Built Up area: 2040 (189.52 sq.m.)                                                                                               4
Super Built up area 2191(203.55 sq.m.)                                                                                           4
Super Built up area 1385(128.67 sq.m.)Built Up area: 940 sq.ft. (87.33 sq.m.)Carpet area: 845 sq.ft. (78.5 sq.m.)                4
Super Built up area 600(55.74 sq.m.)                                                                                             4
Super Built up area 1310(121.7 sq.m.)                                                                                            4
Super Built up area 1790(166.3 sq.m.)                                                                                            4
Super Built up area 1900(176.52 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)                                                  4
Carpet area: 1400 (130.06 sq.m.)                                                                                                 4
Super Built up area 2000(185.81 sq.m.)Built Up area: 1900 sq.ft. (176.52 sq.m.)Carpet area: 1800 sq.ft. (167.23 sq.m.)           4
Super Built up area 650(60.39 sq.m.)                                                                                             4
Super Built up area 1261(117.15 sq.m.)                                                                                           4
Super Built up area 2355(218.79 sq.m.)Built Up area: 1535 sq.ft. (142.61 sq.m.)Carpet area: 1403 sq.ft. (130.34 sq.m.)           4
Super Built up area 1081(100.43 sq.m.)                                                                                           4
Super Built up area 1725(160.26 sq.m.)                                                                                           4
Super Built up area 2358(219.07 sq.m.)                                                                                           4
Super Built up area 1900(176.52 sq.m.)                                                                                           4
Super Built up area 1300(120.77 sq.m.)                                                                                           4
Super Built up area 1430(132.85 sq.m.)                                                                                           4
Super Built up area 2400(222.97 sq.m.)                                                                                           4
Carpet area: 1250 (116.13 sq.m.)                                                                                                 4
Super Built up area 1100(102.19 sq.m.)                                                                                           4
Super Built up area 1825(169.55 sq.m.)                                                                                           4
Carpet area: 1549 (143.91 sq.m.)                                                                                                 4
Super Built up area 1103(102.47 sq.m.)                                                                                           4
Carpet area: 481.73 (44.75 sq.m.)                                                                                                4
Super Built up area 1900(176.52 sq.m.)Built Up area: 1600 sq.ft. (148.64 sq.m.)Carpet area: 1240.04 sq.ft. (115.2 sq.m.)         4
Super Built up area 2802(260.31 sq.m.)Built Up area: 2225.56 sq.ft. (206.76 sq.m.)                                               4
Carpet area: 501 (46.54 sq.m.)                                                                                                   4
Carpet area: 1500 (139.35 sq.m.)                                                                                                 4
Super Built up area 1930(179.3 sq.m.)Built Up area: 1929 sq.ft. (179.21 sq.m.)Carpet area: 1928 sq.ft. (179.12 sq.m.)            4
Super Built up area 1457(135.36 sq.m.)                                                                                           4
Super Built up area 2095(194.63 sq.m.)                                                                                           4
Carpet area: 2290 (212.75 sq.m.)                                                                                                 4
Super Built up area 2950(274.06 sq.m.)                                                                                           4
Built Up area: 1103 (102.47 sq.m.)                                                                                               4
Super Built up area 1789(166.2 sq.m.)                                                                                            4
Carpet area: 1340 (124.49 sq.m.)                                                                                                 4
Super Built up area 1780(165.37 sq.m.)                                                                                           4
Carpet area: 366.08 (34.01 sq.m.)                                                                                                3
Carpet area: 690 (64.1 sq.m.)                                                                                                    3
Built Up area: 2400 (222.97 sq.m.)                                                                                               3
Super Built up area 915(85.01 sq.m.)                                                                                             3
Carpet area: 2298 (213.49 sq.m.)                                                                                                 3
Super Built up area 1743(161.93 sq.m.)                                                                                           3
Super Built up area 2000(185.81 sq.m.)Built Up area: 1900 sq.ft. (176.52 sq.m.)Carpet area: 1850 sq.ft. (171.87 sq.m.)           3
Carpet area: 576 (53.51 sq.m.)                                                                                                   3
Super Built up area 767(71.26 sq.m.)                                                                                             3
Super Built up area 1283(119.19 sq.m.)Built Up area: 978.23 sq.ft. (90.88 sq.m.)Carpet area: 734.43 sq.ft. (68.23 sq.m.)         3
Super Built up area 2120(196.95 sq.m.)Built Up area: 1616 sq.ft. (150.13 sq.m.)                                                  3
Super Built up area 2875(267.1 sq.m.)                                                                                            3
Carpet area: 2500 (232.26 sq.m.)                                                                                                 3
Carpet area: 950 (88.26 sq.m.)                                                                                                   3
Super Built up area 1505(139.82 sq.m.)                                                                                           3
Carpet area: 601 (55.83 sq.m.)                                                                                                   3
Carpet area: 1850 (171.87 sq.m.)                                                                                                 3
Super Built up area 2905(269.88 sq.m.)                                                                                           3
Super Built up area 1799(167.13 sq.m.)Carpet area: 1538 sq.ft. (142.88 sq.m.)                                                    3
Built Up area: 1780 (165.37 sq.m.)                                                                                               3
Built Up area: 1310 (121.7 sq.m.)                                                                                                3
Super Built up area 1490(138.43 sq.m.)Carpet area: 863.91 sq.ft. (80.26 sq.m.)                                                   3
Super Built up area 1095(101.73 sq.m.)                                                                                           3
Super Built up area 1755(163.04 sq.m.)                                                                                           3
Built Up area: 1423 (132.2 sq.m.)                                                                                                3
Super Built up area 2047(190.17 sq.m.)                                                                                           3
Super Built up area 1720(159.79 sq.m.)Carpet area: 1095.3 sq.ft. (101.76 sq.m.)                                                  3
Carpet area: 1750 (162.58 sq.m.)                                                                                                 3

In [ ]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2 Bedrooms,2 Bathrooms,1 Balcony,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2 Bedrooms,2 Bathrooms,2 Balconies,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2 Bedrooms,2 Bathrooms,3 Balconies,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [ ]:
# bedrooms
df['bedRoom'].value_counts()

bedRoom
3 Bedrooms    1437
2 Bedrooms     944
4 Bedrooms     478
1 Bedroom      104
5 Bedrooms      31
6 Bedrooms       3
Name: count, dtype: int64

In [ ]:
df[df['bedRoom'].isnull()]

Empty DataFrame
Columns: [property_name, society, price, price_per_sqft, areaWithType, bedRoom, bathroom, balcony, additionalRoom, address, floorNum, facing, agePossession, nearbyLocations, description, furnishDetails, features, rating]
Index: []

In [ ]:
df['bedRoom'] = df['bedRoom'].str.split(' ').str.get(0).astype('int')

In [ ]:
df.head(1)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2 Bathrooms,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [ ]:
df['bedRoom'].sample(6)

68      2
822     3
819     4
2235    2
1367    3
1336    3
Name: bedRoom, dtype: int64

In [ ]:
# bathroom
df['bathroom'].value_counts()

bathroom
2 Bathrooms    1044
3 Bathrooms     989
4 Bathrooms     636
5 Bathrooms     169
1 Bathroom      112
6 Bathrooms      42
7 Bathrooms       5
Name: count, dtype: int64

In [ ]:
df['bathroom'].isnull().sum()

np.int64(0)

In [ ]:
df['bathroom'] = df['bathroom'].str.split(' ').str.get(0).astype('int')

In [ ]:
df.head(1)

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1 Balcony,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."

In [ ]:
# balcony
df['balcony'].value_counts()

balcony
3 Balconies     974
3+ Balconies    862
2 Balconies     749
1 Balcony       315
No Balcony       97
Name: count, dtype: int64

In [ ]:
df['balcony'].isnull().sum()

np.int64(0)

In [ ]:
df['balcony'] = df['balcony'].str.split(' ').str.get(0).str.replace('No','0')

In [ ]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,NaN,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,NaN,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,NaN,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,Study Room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,Study Room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [ ]:
# additional room
df['additionalRoom'].value_counts()

additionalRoom
Servant Room                                     629
Study Room                                       232
Others                                           179
Pooja Room                                       132
Study Room,Servant Room                           81
Store Room                                        76
Pooja Room,Servant Room                           60
Servant Room,Others                               52
Servant Room,Pooja Room                           30
Study Room,Others                                 27
Pooja Room,Study Room,Servant Room,Others         25
Pooja Room,Study Room,Servant Room                24
Servant Room,Store Room                           19
Pooja Room,Study Room                             13
Pooja Room,Study Room,Servant Room,Store Room     12
Servant Room,Study Room                            8
Study Room,Pooja Room                              8
Study Room,Servant Room,Store Room                 7
Pooja Room,Servant Room,Others                     6
Servant Room,Study Room,Pooja Room,Store Room      6
Pooja Room,Store Room                              6
Others,Servant Room                                6
Pooja Room,Others                                  6
Study Room,Servant Room,Others                     5
Pooja Room,Study Room,Store Room                   4
Pooja Room,Store Room,Study Room,Servant Room      4
Study Room,Pooja Room,Store Room                   3
Store Room,Servant Room                            3
Servant Room,Pooja Room,Study Room,Store Room      3
Servant Room,Others,Pooja Room                     2
Study Room,Servant Room,Pooja Room,Store Room      2
Servant Room,Study Room,Store Room                 2
Study Room,Pooja Room,Servant Room                 2
Servant Room,Others,Store Room,Pooja Room          2
Pooja Room,Study Room,Others                       2
Store Room,Pooja Room,Servant Room                 1
Pooja Room,Study Room,Store Room,Servant Room      1
Pooja Room,Servant Room,Study Room,Store Room      1
Servant Room,Pooja Room,Store Room                 1
Study Room,Servant Room,Store Room,Pooja Room      1
Study Room,Servant Room,Pooja Room                 1
Servant Room,Pooja Room,Store Room,Study Room      1
Study Room,Store Room                              1
Store Room,Study Room                              1
Servant Room,Pooja Room,Study Room                 1
Servant Room,Study Room,Pooja Room                 1
Others,Study Room                                  1
Servant Room,Study Room,Others                     1
Store Room,Pooja Room                              1
Name: count, dtype: int64

In [ ]:
df['additionalRoom'].value_counts().shape

(49,)

In [ ]:
df['additionalRoom'].isnull().sum()

np.int64(1305)

In [ ]:
df['additionalRoom'].fillna('not available')

0                                       not available
1                                       not available
2                                       not available
3                                          Study Room
4                                          Study Room
5                                       not available
6                                       not available
7                                       not available
8                                          Study Room
9                                        Servant Room
10                                      not available
11                                      not available
12                                      not available
13                                      not available
14                                         Study Room
15                                      not available
16                                      not available
17                                      not available
18                                      not available
19                                       Servant Room
20                                         Study Room
21                                       Servant Room
22                                      not available
23                                       Servant Room
24                                       Servant Room
26                                      not available
27                                      not available
28                                       Servant Room
29                                      not available
30                                      not available
31                                      not available
32                                         Pooja Room
33                                      not available
34                                      not available
35                                      not available
36                                             Others
37                                       Servant Room
38                                      not available
39                                      not available
40                                       Servant Room
41                                      not available
42                                       Servant Room
43                                       Servant Room
44                                      not available
45                                      not available
46                            Pooja Room,Servant Room
47                                      not available
48                                      not available
49                                       Servant Room
50                            Study Room,Servant Room
51                                      not available
52                                         Study Room
53                                      not available
54                                      not available
55                                      not available
56                                      not available
57                                      not available
58                                       Servant Room
59                                             Others
60                                         Store Room
61                                         Study Room
62                                       Servant Room
63                                      not available
64                                      not available
65                                      not available
66                                      not available
67                                      not available
68                                      not available
69                                      not available
70                                      not available
71                                      not available
72                                      not available
73                                      not available
74                                       Servant Room
75                                      not available
76                                      not available
77                                      not available
78                                      not available
79                                       Servant Room
80                                      not available
81                                      not available
82                                      not available
83                                       Servant Room
84                                      not available
85                                      not available
86                                       Servant Room
87                                      not available
88                                      not available
89                                             Others
90                                      not available
91                                      not available
92                                      not available
93                                      not available
94                                      not available
95                                      not available
96                                      not available
97                                      not available
98                                      not available
99                                      not available
100                                 Study Room,Others
101                                     not available
102                                     not available
103                                        Study Room
104                                     not available
105                                      Servant Room
106                                      Servant Room
107                                     not available
108                                            Others
109                                     not available
110                                     not available
111                                     not available
112                                     not available
113                                     not available
114                                     not available
115                                     not available
116                                     not available
117                                     not available
118                Pooja Room,Study Room,Servant Room
119                                        Pooja Room
120                                     not available
121                                     not available
122                                     not available
123                                 Study Room,Others
124                                     not available
125                                     not available
126                                     not available
127                                     not available
128                                     not available
129                                     not available
130                                     not available
131                                     not available
132                                     not available
133                                     not available
134                                     not available
135                                     not available
136                           Pooja Room,Servant Room
137                             Pooja Room,Study Room
138                                     not available
139                                        Study Room
140                                      Servant Room
141                                     not available
142                                     not available
143                Study Room,Servant Room,Store Room
144                    Study Room,Servant Room,Others
145                             Pooja Room,Store Room
146                                     not available
147                                     not available
148                                     not available
149                                        Study Room
150                                     not available
151                                     not available
152                                     not available
153                                     not available
154                                     not available
155                                     not available
156                                     not available
157                                     not available
158                                     not available
159                                     not available
160                                     not available
161                                        Study Room
162                                     not available
163                                     not available
164                                     not available
165                                        Store Room
166                                     not available
167                                     not available
168                                        Study Room
169                                            Others
170                                     not available
171                                     not available
172                                     not available
173                                        Study Room
174                                     not available
175                                      Servant Room
176                Pooja Room,Study Room,Servant Room
177                                      Servant Room
178                                     not available
179                                     not available
180                                     not available
181                                     not available
182                                     not available
183                                     not available
184                                     not available
185                                     not available
186                                     not available
187                                     not available
188                                     not available
189                                     not available
190                                     not available
191                                        Study Room
192                                     not available
193                           Study Room,Servant Room
194                                            Others
195                                     not available
196                                     not available
197                                     not available
198                                     not available
199                                     not available
200                                     not available
201                                     not available
202                                     not available
203                                     not available
204                                        Pooja Room
205                                     not available
206                                     not available
207                                     not available
208                                        Study Room
209                                     not available
210                                     not available
211                                     not available
212                                            Others
213                                     not available
214                                     not available
215                Study Room,Servant Room,Store Room
216                                        Study Room
217                                     not available
218                                      Servant Room
219                           Pooja Room,Servant Room
220                                     not available
221                                     not available
222                                     not available
223                                     not available
224                                            Others
225                                     not available
226                                     not available
227                                            Others
228                                            Others
229                                            Others
230                                     not available
231                                     not available
232                                     not available
233                                        Study Room
234                                     not available
235                                     not available
236                                     not available
237                                      Servant Room
238                                     not available
239                                 Study Room,Others
240                                     not available
241                                      Servant Room
242                                     not available
243                                     not available
244                                     not available
245                                      Servant Room
246                                     not available
247                                     not available
248                                        Study Room
249                                     not available
250                                      Servant Room
251                                     not available
252                                     not available
253                                     not available
254                                     not available
255                                        Study Room
256                    Servant Room,Others,Pooja Room
257                                     not available
258                                     not available
259                               Servant Room,Others
260                                     not available
261                                      Servant Room
262                               Servant Room,Others
263                                     not available
264                                     not available
265                                     not available
266                                     not available
267                                     not available
268                                     not available
269                                            Others
270                                     not available
271                                     not available
272                                     not available
273                                     not available
274                                     not available
275                                     not available
276                                            Others
277                                     not available
278                                     not available
279                                     not available
280                                     not available
281                                     not available
282                                     not available
283                                     not available
284                                     not available
285                                      Servant Room
286                           Study Room,Servant Room
287                                        Study Room
288                                      Servant Room
289                                     not available
290                           Servant Room,Store Room
291                                      Servant Room
292                                     not available
293                                     not available
294                                      Servant Room
295                                     not available
296                                     not available
297                                     not available
298                                        Study Room
299                                     not available
300                                      Servant Room
301                                     not available
302                                      Servant Room
303                             Pooja Room,Study Room
304                  Pooja Room,Study Room,Store Room
305                               Servant Room,Others
306                                     not available
307                                      Servant Room
308                                      Servant Room
309                                     not available
310                                      Servant Room
311                                     not available
312                                     not available
313                                        Study Room
314                                      Servant Room
315                                      Servant Room
316                                     not available
317                                     not available
318                                            Others
319                                        Study Room
320                                      Servant Room
321                                     not available
322                           Servant Room,Store Room
323                                      Servant Room
324                                     not available
325                                     not available
326                                     not available
327                                      Servant Room
328                                     not available
329                                      Servant Room
330                             Pooja Room,Study Room
331                  Pooja Room,Study Room,Store Room
332                               Servant Room,Others
333                                     not available
334                                      Servant Room
335                                      Servant Room
336                                     not available
337                                      Servant Room
338                                      Servant Room
339                                     not available
340                                     not available
341                                      Servant Room
342                                            Others
343                           Study Room,Servant Room
344                                     not available
345                                        Study Room
346                                     not available
347         Pooja Room,Study Room,Servant Room,Others
348                                            Others
349                                      Servant Room
350                                     not available
351                                     not available
352                                     not available
353                                      Servant Room
354                           Study Room,Servant Room
355                                     not available
356                                        Study Room
357                                      Servant Room
358                                        Study Room
359                                      Servant Room
360                                      Servant Room
361                                      Servant Room
362                                      Servant Room
363                                     not available
364                                      Servant Room
365                           Pooja Room,Servant Room
366                           Pooja Room,Servant Room
367                                     not available
368                                     not available
369                Study Room,Servant Room,Store Room
370                                      Servant Room

In [ ]:
df['additionalRoom'] = df['additionalRoom'].str.lower()

In [ ]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4th of 4 Floors,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1st of 3 Floors,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12nd of 14 Floors,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2nd of 4 Floors,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5th of 8 Floors,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [ ]:
# address -> needs feature engineering

In [ ]:
# floor
df['floorNum']

0              4th   of 4 Floors
1              1st   of 3 Floors
2            12nd   of 14 Floors
3              2nd   of 4 Floors
4              5th   of 8 Floors
5              3rd   of 3 Floors
6             5th   of 25 Floors
7            14th   of 27 Floors
8              2nd   of 3 Floors
9            31st   of 40 Floors
10             1st   of 4 Floors
11            4th   of 13 Floors
12            4th   of 15 Floors
13            3rd   of 20 Floors
14           13rd   of 13 Floors
15           25th   of 25 Floors
16            Ground of 1 Floors
17           Ground of 14 Floors
18           11st   of 14 Floors
19           12nd   of 13 Floors
20             4th   of 4 Floors
21           11st   of 22 Floors
22             4th   of 4 Floors
23           Ground of 14 Floors
24           10th   of 25 Floors
26             3rd   of 3 Floors
27           20th   of 20 Floors
28            5th   of 17 Floors
29            4th   of 12 Floors
30             4th   of 4 Floors
31             1st   of 4 Floors
32           12nd   of 12 Floors
33            8th   of 12 Floors
34           20th   of 20 Floors
35             8th   of 8 Floors
36           21st   of 24 Floors
37           Ground of 11 Floors
38            6th   of 19 Floors
39            1st   of 19 Floors
40             1st   of 3 Floors
41           12nd   of 17 Floors
42            6th   of 24 Floors
43            1st   of 25 Floors
44             2nd   of 4 Floors
45             1st   of 4 Floors
46            9th   of 29 Floors
47             5th   of 8 Floors
48           18th   of 32 Floors
49           29th   of 31 Floors
50             3rd   of 5 Floors
51            3rd   of 26 Floors
52            5th   of 18 Floors
53             1st   of 4 Floors
54            9th   of 12 Floors
55            6th   of 10 Floors
56             2nd   of 4 Floors
57           14th   of 14 Floors
58            1st   of 11 Floors
59            8th   of 14 Floors
60             2nd   of 2 Floors
61           12nd   of 12 Floors
62            4th   of 14 Floors
63            1st   of 18 Floors
64            7th   of 19 Floors
65             3rd   of 4 Floors
66            5th   of 20 Floors
67            9th   of 15 Floors
68           14th   of 17 Floors
69           14th   of 14 Floors
70           15th   of 20 Floors
71            6th   of 14 Floors
72            6th   of 14 Floors
73            2nd   of 12 Floors
74            3rd   of 11 Floors
75             2nd   of 4 Floors
76            4th   of 13 Floors
77             3rd   of 4 Floors
78            6th   of 14 Floors
79            8th   of 13 Floors
80             2nd   of 4 Floors
81             4th   of 4 Floors
82           Ground of 14 Floors
83           11st   of 11 Floors
84             1st   of 3 Floors
85           11st   of 13 Floors
86           21st   of 41 Floors
87            4th   of 13 Floors
88             2nd   of 5 Floors
89             2nd   of 3 Floors
90             4th   of 4 Floors
91           32nd   of 32 Floors
92             2nd   of 4 Floors
93             2nd   of 2 Floors
94             2nd   of 2 Floors
95           11st   of 11 Floors
96           23rd   of 26 Floors
97            6th   of 12 Floors
98            9th   of 20 Floors
99             1st   of 4 Floors
100           5th   of 15 Floors
101            43   of 47 Floors
102            1st   of 1 Floors
103            1st   of 4 Floors
104           1st   of 13 Floors
105          11st   of 12 Floors
106          14th   of 24 Floors
107           9th   of 30 Floors
108           8th   of 14 Floors
109            9th   of 9 Floors
110           2nd   of 12 Floors
111           4th   of 14 Floors
112          32nd   of 55 Floors
113            43   of 47 Floors
114           2nd   of 19 Floors
115            3rd   of 4 Floors
116           8th   of 22 Floors
117            3rd   of 4 Floors
118          20th   of 32 Floors
119           2nd   of 17 Floors
120        Basement of 28 Floors
121           4th   of 10 Floors
122           Ground of 4 Floors
123            3rd   of 4 Floors
124            4th   of 8 Floors
125            3rd   of 4 Floors
126           6th   of 20 Floors
127          13rd   of 13 Floors
128          13rd   of 13 Floors
129          16th   of 16 Floors
130            3rd   of 4 Floors
131           Ground of 1 Floors
132          11st   of 14 Floors
133           2nd   of 14 Floors
134          12nd   of 12 Floors
135            2nd   of 4 Floors
136           1st   of 18 Floors
137           4th   of 12 Floors
138          11st   of 13 Floors
139           5th   of 17 Floors
140           1st   of 25 Floors
141          12nd   of 16 Floors
142          16th   of 18 Floors
143            6th   of 6 Floors
144            2nd   of 2 Floors
145            3rd   of 4 Floors
146          11st   of 25 Floors
147          10th   of 18 Floors
148           2nd   of 25 Floors
149            4th   of 4 Floors
150          19th   of 41 Floors
151            1st   of 3 Floors
152            8th   of 8 Floors
153          18th   of 19 Floors
154          10th   of 16 Floors
155           7th   of 20 Floors
156           2nd   of 14 Floors
157          10th   of 10 Floors
158           5th   of 12 Floors
159          10th   of 20 Floors
160          20th   of 34 Floors
161          20th   of 22 Floors
162            3rd   of 4 Floors
163          13rd   of 14 Floors
164           3rd   of 19 Floors
165           7th   of 18 Floors
166            4th   of 4 Floors
167           4th   of 14 Floors
168            2nd   of 4 Floors
169           2nd   of 25 Floors
170           4th   of 14 Floors
171           3rd   of 19 Floors
172            1st   of 1 Floors
173            2nd   of 4 Floors
174          11st   of 15 Floors
175          11st   of 21 Floors
176          16th   of 22 Floors
177           8th   of 10 Floors
178           1st   of 35 Floors
179          18th   of 25 Floors
180           8th   of 15 Floors
181                          NaN
182           2nd   of 16 Floors
183          17th   of 17 Floors
184          23rd   of 28 Floors
185          10th   of 18 Floors
186          30th   of 32 Floors
187            4th   of 4 Floors
188            2nd   of 3 Floors
189           Ground of 3 Floors
190          Ground of 14 Floors
191            1st   of 4 Floors
192            1st   of 1 Floors
193          11st   of 36 Floors
194          11st   of 13 Floors
195           Ground of 3 Floors
196          19th   of 19 Floors
197          28th   of 28 Floors
198            4th   of 4 Floors
199            9th   of 9 Floors
200            7th   of 7 Floors
201         Basement of 4 Floors
202          15th   of 15 Floors
203           2nd   of 34 Floors
204          Ground of 14 Floors
205           9th   of 10 Floors
206           1st   of 15 Floors
207            1st   of 1 Floors
208           4th   of 34 Floors
209           4th   of 18 Floors
210           3rd   of 15 Floors
211            1st   of 4 Floors
212           1st   of 19 Floors
213     Lower Ground of 4 Floors
214          13rd   of 13 Floors
215           4th   of 40 Floors
216           6th   of 18 Floors
217          20th   of 47 Floors
218          27th   of 48 Floors
219            6th   of 7 Floors
220          33rd   of 48 Floors
221          35th   of 35 Floors
222          26th   of 47 Floors
223           Ground of 1 Floors
224            2nd   of 4 Floors
225           4th   of 14 Floors
226          10th   of 17 Floors
227          11st   of 14 Floors
228          10th   of 22 Floors
229          Ground of 24 Floors
230           3rd   of 12 Floors
231           7th   of 25 Floors
232           8th   of 14 Floors
233            2nd   of 4 Floors
234           3rd   of 18 Floors
235            1st   of 4 Floors
236           9th   of 14 Floors
237          14th   of 15 Floors
238            4th   of 4 Floors
239           8th   of 25 Floors
240          10th   of 14 Floors
241           3rd   of 14 Floors
242            3rd   of 4 Floors
243            2nd   of 4 Floors
244           3rd   of 14 Floors
245            7th   of 7 Floors
246            2nd   of 4 Floors
247           3rd   of 15 Floors
248           8th   of 34 Floors
249          12nd   of 14 Floors
250           8th   of 42 Floors
251            1st   of 4 Floors
252           1st   of 22 Floors
253          26th   of 34 Floors
254          21st   of 29 Floors
255           8th   of 32 Floors
256           2nd   of 14 Floors
257           1st   of 12 Floors
258            2nd   of 4 Floors
259          39th   of 40 Floors
260           1st   of 14 Floors
261           8th   of 10 Floors
262            2nd   of 3 Floors
263            3rd   of 4 Floors
264            7th   of 9 Floors
265           4th   of 15 Floors
266          22nd   of 24 Floors
267          14th   of 20 Floors
268          11st   of 15 Floors
269          17th   of 17 Floors
270           3rd   of 12 Floors
271          12nd   of 13 Floors
272           8th   of 19 Floors
273           3rd   of 14 Floors
274          14th   of 14 Floors
275            7th   of 7 Floors
276           9th   of 15 Floors
277           2nd   of 17 Floors
278            3rd   of 3 Floors
279            6th   of 6 Floors
280          16th   of 16 Floors
281          12nd   of 12 Floors
282            1st   of 1 Floors
283            4th   of 4 Floors
284          17th   of 17 Floors
285           7th   of 26 Floors
286          11st   of 30 Floors
287            4th   of 8 Floors
288           1st   of 14 Floors
289           6th   of 14 Floors
290            1st   of 3 Floors
291          17th   of 17 Floors
292            1st   of 7 Floors
293          16th   of 18 Floors
294          19th   of 40 Floors
295          31st   of 32 Floors
296          14th   of 22 Floors
297           5th   of 19 Floors
298            2nd   of 4 Floors
299            1st   of 4 Floors
300           1st   of 10 Floors
301          15th   of 32 Floors
302            1st   of 7 Floors
303            1st   of 2 Floors
304            2nd   of 3 Floors
305          11st   of 14 Floors
306           9th   of 26 Floors
307          33rd   of 42 Floors
308          14th   of 18 Floors
309            4th   of 4 Floors
310           5th   of 14 Floors
311          18th   of 18 Floors
312           1st   of 14 Floors
313          20th   of 23 Floors
314           9th   of 14 Floors
315          18th   of 19 Floors
316           8th   of 32 Floors
317           4th   of 15 Floors
318           9th   of 17 Floors
319            4th   of 8 Floors
320           1st   of 14 Floors
321           6th   of 14 Floors
322            1st   of 3 Floors
323          19th   of 40 Floors
324          31st   of 32 Floors
325           5th   of 19 Floors
326            1st   of 4 Floors
327           1st   of 10 Floors
328          15th   of 32 Floors
329            1st   of 7 Floors
330            1st   of 2 Floors
331            2nd   of 3 Floors
332          11st   of 14 Floors
333           9th   of 26 Floors
334          14th   of 18 Floors
335           5th   of 14 Floors
336           1st   of 14 Floors
337           9th   of 14 Floors
338          18th   of 19 Floors
339           4th   of 15 Floors
340           1st   of 44 Floors
341          20th   of 20 Floors
342          24th   of 31 Floors
343           2nd   of 15 Floors
344            4th   of 4 Floors
345          14th   of 14 Floors
346           9th   of 16 Floors
347          14th   of 15 Floors
348           4th   of 14 Floors
349          26th   of 30 Floors
350           2nd   of 16 Floors
351          14th   of 24 Floors
352          17th   of 17 Floors
353           2nd   of 14 Floors
354          25th   of 25 Floors
355           9th   of 22 Floors
356            4th   of 4 Floors
357           6th   of 17 Floors
358           5th   of 14 Floors
359           4th   of 14 Floors
360          14th   of 21 Floors
361          15th   of 19 Floors
362           7th   of 14 Floors
363            2nd   of 4 Floors
364          16th   of 20 Floors
365          24th   of 51 Floors
366          10th   of 20 Floors
367            2nd   of 4 Floors
368           2nd   of 12 Floors
369           2nd   of 24 Floors
370           1st   of 19 Floors
371           8th   of 18 Floors
372          12nd   of 22 Floors
373          18th   of 19 Floors
374            1st   of 4 Floors
375           2nd   of 36 Floors
376            3rd   of 4 Floors
377          11st   of 11 Floors
378           7th   of 20 Floors
379           5th   of 18 Floors
380           6th   of 12 Floors
381          19th   of 31 Floors
382          25th   of 25 Floors
383          10th   of 10 Floors
384          10th   of 10 Floors
385            3rd   of 9 Floors
386           8th   of 14 Floors
387           5th   of 12 Floors
388           4th   of 22 Floors
389           1st   of 35 Floors
390          10th   of 14 Floors
391          16th   of 24 Floors
392          10th   of 14 Floors
393            3rd   of 8 Floors
394          17th   of 19 Floors
395           9th   of 14 Floors
396          11st   of 26 Floors
397          19th   of 20 Floors
398          Ground of 16 Floors
399          Ground of 23 Floors
400           8th   of 26 Floors
401           4th   of 11 Floors
402          30th   of 32 Floors
403          16th   of 51 Floors
404          18th   of 21 Floors
405           2nd   of 10 Floors
406           7th   of 10 Floors
407            2nd   of 4 Floors
408          10th   of 10 Floors
409           9th   of 12 Floors
410           6th   of 10 Floors
411          14th   of 29 Floors
412          25th   of 36 Floors
413           7th   of 23 Floors
414           4th   of 14 Floors
415            7th   of 9 Floors
416          18th   of 32 Floors
417          12nd   of 17 Floors
418            3rd   of 4 Floors
419          21st   of 28 Floors
420          14th   of 28 Floors
421           5th   of 25 Floors
422           3rd   of 19 Floors
423          19th   of 24 Floors
424          10th   of 14 Floors
425            5th   of 9 Floors
426          10th   of 30 Floors
427           7th   of 14 Floors
428          11st   of 20 Floors
429           2nd   of 17 Floors
430            2nd   of 4 Floors
431           7th   of 14 Floors
432           6th   of 14 Floors
433          11st   of 17 Floors
434           9th   of 14 Floors
435            4th   of 4 Floors
436          14th   of 20 Floors
437            5th   of 5 Floors
438            1st   of 4 Floors
439          16th   of 27 Floors
440           1st   of 10 Floors
441          18th   of 32 Floors
442           6th   of 16 Floors
443           8th   of 13 Floors
444            4th   of 4 Floors
445           7th   of 27 Floors
446            9th   of 9 Floors
447            3rd   of 4 Floors
448          11st   of 18 Floors
449          17th   of 25 Floors
450           7th   of 42 Floors
451           5th   of 30 Floors
452          16th   of 32 Floors
453           2nd   of 16 Floors
454           8th   of 29 Floors
455            2nd   of 8 Floors
456           3rd   of 32 Floors
457           6th   of 26 Floors
458          Ground of 14 Floors
459           2nd   of 12 Floors
460          15th   of 40 Floors
461          10th   of 25 Floors
462          11st   of 30 Floors
463          10th   of 15 Floors
464           4th   of 12 Floors
465           3rd   of 18 Floors
466           9th   of 19 Floors
467           8th   of 16 Floors
468           7th   of 12 Floors
469           5th   of 12 Floors
470           7th   of 14 Floors
471           7th   of 14 Floors
472           9th   of 14 Floors
473           2nd   of 20 Floors
474           5th   of 18 Floors
475          11st   of 20 Floors
476           8th   of 11 Floors
477           7th   of 17 Floors
478          20th   of 26 Floors
479          10th   of 12 Floors
480           7th   of 29 Floors
481          10th   of 51 Floors
482          16th   of 21 Floors
483           8th   of 21 Floors
484           1st   of 14 Floors
485          18th   of 30 Floors
486          15th   of 30 Floors
487          25th   of 30 Floors
488           5th   of 29 Floors
489           9th   of 26 Floors
490           5th   of 26 Floors
491           7th   of 26 Floors
492           7th   of 26 Floors
493           7th   of 26 Floors
494          12nd   of 30 Floors
495           5th   of 15 Floors
496           4th   of 10 Floors
497           6th   of 10 Floors
498            3rd   of 6 Floors
499          10th   of 18 Floors
500          15th   of 28 Floors
501          15th   of 28 Floors
502          10th   of 14 Floors
503           9th   of 28 Floors
504          10th   of 15 Floors
505          10th   of 21 Floors
506           9th   of 12 Floors
507           Ground of 4 Floors
508            1st   of 2 Floors
509          11st   of 12 Floors
510          17th   of 24 Floors
511           1st   of 26 Floors
512          Ground of 18 Floors
513           7th   of 14 Floors
514            5th   of 8 Floors
515          12nd   of 29 Floors
516          14th   of 29 Floors
517          14th   of 29 Floors
518           9th   of 21 Floors
519          19th   of 29 Floors
520           8th   of 14 Floors
521          14th   of 29 Floors
522           8th   of 14 Floors
523            2nd   of 5 Floors
524           9th   of 13 Floors
525           5th   of 14 Floors
526          Ground of 14 Floors
527            6th   of 8 Floors
528          10th   of 19 Floors
529           6th   of 10 Floors
530           8th   of 18 Floors
531           9th   of 24 Floors
532           9th   of 26 Floors
533          12nd   of 17 Floors
534          11st   of 16 Floors
535           6th   of 16 Floors
536          15th   of 39 Floors
537           7th   of 12 Floors
538           8th   of 19 Floors
539           8th   of 26 Floors
540           3rd   of 26 Floors
541          10th   of 26 Floors
542           1st   of 26 Floors
543           4th   of 26 Floors
544           5th   of 12 Floors
545           2nd   of 12 Floors
546          20th   of 40 Floors
547          13rd   of 40 Floors
548           8th   of 40 Floors
549           8th   of 19 Floors
550          16th   of 19 Floors
551          12nd   of 18 Floors
552          10th   of 19 Floors
553           6th   of 15 Floors
554          16th   of 19 Floors
555           8th   of 16 Floors
556          12nd   of 15 Floors
557          12nd   of 18 Floors
558           5th   of 22 Floors
559           9th   of 42 Floors
560           7th   of 14 Floors
561           7th   of 12 Floors
562           7th   of 12 Floors
563           5th   of 16 Floors
564           8th   of 31 Floors
565           7th   of 21 Floors
566           5th   of 29 Floors
567           9th   of 30 Floors
568          11st   of 29 Floors
569          10th   of 19 Floors
570           6th   of 31 Floors
571            3rd   of 9 Floors
572          22nd   of 30 Floors
573           5th   of 20 Floors
574          15th   of 29 Floors
575           5th   of 14 Floors
576          Ground of 14 Floors
577           6th   of 14 Floors
578           1st   of 24 Floors
579            2nd   of 8 Floors
580          12nd   of 19 Floors
581          12nd   of 25 Floors
582           6th   of 17 Floors
583           8th   of 18 Floors
584            4th   of 5 Floors
585           5th   of 25 Floors
586           2nd   of 19 Floors
587          20th   of 30 Floors
588          12nd   of 14 Floors
589          18th   of 19 Floors
590           2nd   of 26 Floors
591           3rd   of 15 Floors
592           3rd   of 19 Floors
593          18th   of 51 Floors
594           7th   of 27 Floors
595          17th   of 19 Floors
596           8th   of 14 Floors
597           2nd   of 19 Floors
598           8th   of 19 Floors
599           9th   of 30 Floors
600           3rd   of 18 Floors
601          12nd   of 23 Floors
602          10th   of 28 Floors
603            2nd   of 5 Floors
604          Ground of 21 Floors
605           7th   of 16 Floors
606            2nd   of 9 Floors

In [ ]:
df['floorNum'].isnull().sum()

np.int64(2)

In [ ]:
df[df['floorNum'].isnull()]

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
181,3 BHK Flat in Dwarka Expressway Gurgaon,experion heartsong,1.08,6150.0,Built Up area: 1758 (163.32 sq.m.),3,3,0,not available,"604, Tower B-3, 6th Floor,Sector 108, Dwarka E...",NaN,NaN,Under Construction,NaN,A property by one of the most reputed builders...,[],NaN,NaN
2766,2 BHK Flat in Sector 78 Gurgaon,nan,0.60,3692.0,Built Up area: 1625 (150.97 sq.m.),2,2,0,not available,"Gurgaon, Sector 78 Gurgaon, Gurgaon, Haryana",NaN,NaN,Under Construction,NaN,The property is under construction it's by rah...,[],NaN,"['Safety4 out of 5', 'Lifestyle4 out of 5', 'E..."

In [ ]:
df['floorNum'] = df['floorNum'].str.split(' ').str.get(0).replace('Ground','0').str.replace('Basement','-1').str.replace('Lower','0').str.extract(r'(\d+)')

In [ ]:
df.head()

,property_name,society,price,price_per_sqft,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,maa bhagwati residency,0.45,5000.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,apna enclave,0.50,7692.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,tulsiani easy in homes,0.40,6722.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,smart world orchard,1.47,12250.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2,NaN,Dec-23,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,parkwood westend,0.70,5204.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [ ]:
# facing
df['facing'].value_counts()

facing
North-East    505
East          490
North         301
South         203
West          183
North-West    162
South-East    144
South-West    135
Name: count, dtype: int64

In [ ]:
df['facing'].fillna('NA',inplace=True)

/tmp/ipykernel_1262/3692945726.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['facing'].fillna('NA',inplace=True)